name: server

on:
  workflow_dispatch:
  push:
    paths:
      - "server/app-sm-context/**"
    branches:
      - "staging"
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r server/requirements.txt

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker Staging Build
        uses: docker/build-push-action@v4
        with:
          context: server/app-sm-context
          push: true
          tags: hicsail/stem-equity-coach-sm:staging
